Online-Pluisje-Art/Operation-Blackwell

- README.md
> meta: Update readme

- Assets/Scenes/CameraMovementTest.unity
- Assets/Scenes/MovementScene.unity.meta
- Assets/Scripts/CameraController.cs
- Assets/Scripts/CameraMovement.cs
- Assets/Scripts/Grid.cs
- Assets/Scripts/ICameraMovementController.cs
- Assets/Scripts/Main.asmdef
- Assets/Scripts/MovementController.cs
This PR fixes the compilation errors created by ordering classes in files in new namespaces. This was done to keep a layer of separation between classes.
> Fixup all the compilation errors

- ProjectSettings/ProjectSettings.asset
> meta: Bump version, starting a new development cycle

- .github/workflows/build.yml
Attempt one at integrating autobuilds.
> meta: Add auto build of Operation Blackwell

- Assets/Scenes/MapEditor.unity
- Assets/Scripts/Core/GameController.cs
- Assets/Scripts/Core/Grid.cs
> Fix the map editor

- Assets/Resources/Prefabs/Weapons/Pistol.prefab
- Assets/Resources/Prefabs/Weapons/Sword.prefab
- Assets/Scenes/TutorialLevel.unity
- Assets/Scripts/Core/CoreUnit.cs
- Assets/Scripts/Core/GridCombatSystem.cs
- Assets/Scripts/Player/UnitGridCombat.cs
- Assets/Scripts/Player/Weapons/Weapon.cs
- Assets/Scripts/UI/HUDController.cs
This PR wires up weapon switching and adds a ranged weapon to the player. Supersedes #60
OPA-30 and OPA-31
> core: Implement ranged weapons and weapon switching

- Assets/Resources/Prefabs/Interactables/Crate.prefab
- Assets/Scenes/TutorialLevel.unity
- Assets/Scripts/Core/GridCombatSystem.cs
- Assets/Scripts/Core/Interactables.meta
- Assets/Scripts/Core/Interactables/Crate.cs
- Assets/Scripts/Core/Interactables/Crate.cs.meta
- Assets/Scripts/Core/Interactables/IInteractable.cs
- Assets/Scripts/Core/Interactables/IInteractable.cs.meta
- Assets/Scripts/Core/Tilemap.cs
- Assets/Scripts/Player/UnitGridCombat.cs
This PR adds the ability to make interactables by creating a new script for that interactable and adding it to a prefab.
> Add basic interactables through an interface

- Assets/Scripts/Core/GridCombatSystem.cs
- Assets/Scripts/Core/Pathfinding/GridPathfinding.cs
- Assets/Scripts/Core/Pathfinding/PathNode.cs
- Assets/Scripts/Core/Tilemap.cs
This PR will update the pathfinding so that players will move around other players. Please test  this before merging to make sure I did not forget any edge-cases.
> Pathfinding update

- Assets/Scenes/MainMenu.unity
- Assets/Scenes/TutorialLevel.unity
- ProjectSettings/ProjectSettings.asset
Starting with the 0.5 'Taygete' development cycle. Also doing some cleanup tasks.
> meta: Bump version to 0.5 'Taygete'

- ProjectSettings/ProjectSettings.asset
Starting with the 0.6 'Electra' development cycle.
> meta: Update version to 0.6 'Electra'

- Assets/Resources/Textures/Cutscenes/Overlay/CutsceneBase.png.meta
- Assets/Resources/Textures/Cutscenes/Overlay/CutsceneBaseNoButtons.png.meta
- Assets/Resources/Textures/Cutscenes/Overlay/CutsceneLeft.png.meta
- Assets/Resources/Textures/Cutscenes/Overlay/CutsceneLeftPress.png.meta
- Assets/Resources/Textures/Cutscenes/Overlay/CutsceneRight.png.meta
- Assets/Resources/Textures/Cutscenes/Overlay/CutsceneRightEnd.png.meta
- Assets/Resources/Textures/Cutscenes/Overlay/CutsceneRightPress.png.meta
- Assets/Resources/Textures/HUD/MainMenuBGPlaceholder.png.meta
- Assets/Resources/Textures/HUD/SquareDashes.png.meta
- Assets/Resources/Textures/HUD/SquareDashesRed.png.meta
- Assets/Resources/Textures/HUD/White_1x1.psd.meta
- Assets/Scenes/TutorialLevel.unity
As the pixel perfect UI was causing us a lot of pain, we decided to remove it. This PR reverts all changes in that department.
> everywhere: Remove pixel perfect UI

- Assets/Resources/Prefabs/Interactables/Puzzle.prefab
- Assets/Resources/Prefabs/Interactables/Puzzle.prefab.meta
- Assets/Scripts/Core/Interactables/PuzzleTrigger.cs
- Assets/Scripts/Core/Interactables/PuzzleTrigger.cs.meta
- Assets/Scripts/Core/Puzzles/PuzzleController.cs
Signed-off-by: Noah Knegt <github@noahknegt.com>
> core: Add puzzle triggers based on puzzle id

- ProjectSettings/ProjectSettings.asset
Starting with the 0.7 'Maia' development cycle.
> meta: Update version to 0.7 'Maia'

- Assets/Scripts/Core/Controllers/GameController.cs
- Assets/Scripts/Core/Controllers/GridCombatSystem.cs
- Assets/Scripts/Core/Grid/Tilemap.cs
- Assets/Scripts/Core/Unit/CoreUnit.cs
- Assets/Scripts/Player/UnitGridCombat.cs
This PR adds optimisations on whenever the game draws new visuals and will remove the redrawing things that are not changed.
> Optimisations

- Assets/Scripts/Core/Controllers/GridCombatSystem.cs
- Assets/Scripts/Core/Pathfinding/BinaryTree.cs
- Assets/Scripts/Core/Pathfinding/GridPathfinding.cs
- Assets/Scripts/Core/Pathfinding/Heap.cs
- Assets/Scripts/Core/Pathfinding/Heap.cs.meta
- Assets/Scripts/Core/Pathfinding/PathNode.cs
- Assets/Scripts/Core/Utils/PrefabStatus.cs
This PR implements a new version of the pathfinding. It also adds the possibility for "heap" optimisation, but that does not fully work yet, that will be fixed at a later point.
> core: Adds new pathfinding, heap class but that does not work yet

- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Mid.asset
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Opening.asset
- Assets/Scenes/TutorialLevel.unity
This PR fixes the text being way too small. Now it should be decently readable.
> cutscenes: Fix the opening cutscene text size

- Assets/Scenes/Final Level.unity
Extension of #108, I forgot the other level already in the game.
> finallevel: fix cutscene text size

- Assets/StreamingAssets/SavesWorld/tutorial_V4.2_2.json
- Assets/StreamingAssets/SavesWorld/tutorial_V4.2_2.json.meta
Finally, decent performance!
Expect a new PR for the final level and any other levels if needed.
> tutorial: Fix walkable nodes outside the map, improving performance

- Assets/Scenes/TutorialLevel.unity
This Pr fixes the errors, that for some reason are still present, in the wire overlays for the walls.
> scene: Fix the order of the wire wall overlays

- Assets/Scripts/Puzzles/PuzzleController.cs
This PR fixes the resetting of the timer once a puzzle is finished.
> puzzles: Fix timer reset

- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 1.asset
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 1.asset.meta
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 2.asset
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 2.asset.meta
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 3.asset
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 3.asset.meta
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 4.asset
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 4.asset.meta
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 5.asset
- Assets/Resources/ScriptableObjects/CutsceneObjects/Scenes/Level 1/Tutorial 5.asset.meta
- Assets/Scenes/TutorialLevel.unity
Added tutorial explanation cutscenes, added combat triggers and fixed cutscene triggers.
Signed-off-by: drfdaniel <d.flederus@outlook.com>
> Reworked level 1 with cutscenes and triggers

- Assets/Resources/Prefabs/Puzzles/Puzzles.prefab
- Assets/Scripts/LevelTransitions/LevelTransitions.asmdef
- Assets/Scripts/Puzzles/Puzzle.cs
- Assets/Scripts/Puzzles/PuzzleController.cs
- Assets/Scripts/UI/Cursor/CursorController.cs
This PR updates some existing features to make the game a bit easier to use and play.
> Level transitions

- Assets/Scenes/Final Level.unity
- Assets/Scenes/MapEditor.unity
- Assets/Scenes/TutorialLevel.unity
- Assets/Scripts/Core/Controllers/GameController.cs
- Assets/Scripts/Core/Controllers/SaveController.cs
- Assets/StreamingAssets/SavesWorld/finallevel_V1.5.json
- Assets/StreamingAssets/SavesWorld/finallevel_V1.5.json.meta
- Assets/StreamingAssets/SavesWorld/finallevel_V1.6.json
- Assets/StreamingAssets/SavesWorld/finallevel_V1.6.json.meta
- Assets/StreamingAssets/SavesWorld/tutorial_V4.3.json
- Assets/StreamingAssets/SavesWorld/tutorial_V4.3.json.meta
- Assets/StreamingAssets/SavesWorld/tutorial_V4.4.json
- Assets/StreamingAssets/SavesWorld/tutorial_V4.4.json.meta
- Assets/StreamingAssets/SavesWorld/tutorial_V4.5.json
- Assets/StreamingAssets/SavesWorld/tutorial_V4.5.json.meta
reworked final level. Dimensions match with tutorial level now
> Reworkfinallevel

- Assets/Scripts/Core/Unit/CoreUnit.cs
- Assets/Scripts/Player/AIUnit.cs
- Assets/Scripts/Player/UnitGridCombat.cs
This PR moves even more parts of the units to the core unit to remove the duplication of code.
> core: Move the awake to the base for same components

- ProjectSettings/EditorBuildSettings.asset
This fixes build issues introduced by ba06fe9422036ff0cc8e2f0e4587617fda53bb32
> build: Remove deleted scene

- Assets/Resources/Prefabs/Controllers/Global Controller.prefab
- Assets/Resources/Prefabs/Controllers/Global Controller.prefab.meta
- Assets/Scenes/MainMenu.unity
- Assets/Scenes/TutorialLevel.unity
- Assets/Scripts/Core/Controllers/GameController.cs
- Assets/Scripts/Core/Controllers/GlobalController.cs
- Assets/Scripts/Core/Controllers/GlobalController.cs.meta
- Assets/Scripts/Core/Interactables/PuzzleTrigger.cs
- Assets/Scripts/LevelTransitions/LevelTransitionController.cs
- Assets/Scripts/Puzzles/PuzzleController.cs
This PR adds a global controller that keeps a state for all the levels (completion and scene name) for now it will reset once you close the game but if you save this it can be used to load previous levels. And this PR fixes the puzzle tile on completion.
> Global controller

- Assets/Scripts/Core/Interactables/PuzzleTrigger.cs
- Assets/Scripts/Core/Unit/CoreUnit.cs
- Assets/Scripts/Player/UnitGridCombat.cs
- Assets/Scripts/Puzzles/Puzzle.cs
- Assets/Scripts/Puzzles/PuzzleController.cs
This PR add the ability to caleana to make a puzzle 1 level easier unless the puzzle is already on easy.
> puzzles: Make the puzzle 1 level easier for caleana

- ProjectSettings/ProjectSettings.asset
This PR pushes the version to `0.9 'Pleione'` this PR is blocked on #136.
> meta: Update version to 0.9 'Pleione'

- Assets/Scenes/PrisonLevel.unity
- Assets/Scripts/Core/Utils/WeaponSwitcher.cs
- ProjectSettings/ProjectSettings.asset
This PR allows window resizing, fixes a missing cutscene, adds the correct level transition between level 2 and 3 and addresses some issues found in #150.
> Some small bugfixes

- Assets/Resources/Animations/Credits.meta
- Assets/Resources/Animations/Credits/CreditAnimator.anim
- Assets/Resources/Animations/Credits/CreditAnimator.anim.meta
- Assets/Resources/Animations/Credits/Text (TMP).controller
- Assets/Resources/Animations/Credits/Text (TMP).controller.meta
- Assets/Scenes/CreditScreen.unity
- Assets/Scenes/CreditScreen.unity.meta
- Assets/Scenes/MainMenu.unity
- Assets/Scenes/WinScreen.unity
- Assets/Scripts/Core/Controllers/CreditController.cs
- Assets/Scripts/Core/Controllers/CreditController.cs.meta
- Assets/Scripts/Core/Controllers/GlobalController.cs
- Assets/Scripts/Core/Utils/Levelswitcher.cs
- Assets/Scripts/UI/Menus/GraphicsOptionsMenu.cs
- ProjectSettings/EditorBuildSettings.asset
This PR adds a credit screen, made it accessible from the main menu, adds a continue button on the main menu and fixes a bug in level loading.
> Add a credit screen and perform bug fixes
